### ISSUE TITLE
使用silk4j生成音频时出错

### ISSUE THREAD

**Issue by OctoFlareDev** [whiterasbk/MiraiMidiProduce#11]
```
MiderBot: Exception in coroutine Plugin org.mider.produce.bot of MiderBot
java.lang.UnsatisfiedLinkError: 'void io.github.mzdluo123.silk4j.LameCoder.initDecoder()'
	at mider-bot-0.1.8-bundled-silk4j.mirai2.jar//io.github.mzdluo123.silk4j.LameCoder.initDecoder(Native Method)
	at mider-bot-0.1.8-bundled-silk4j.mirai2.jar//io.github.mzdluo123.silk4j.LameCoder.decode(LameCoder.java:59)
	at mider-bot-0.1.8-bundled-silk4j.mirai2.jar//io.github.mzdluo123.silk4j.AudioUtils.mp3ToSilk(AudioUtils.java:29)
	at mider-bot-0.1.8-bundled-silk4j.mirai2.jar//io.github.mzdluo123.silk4j.AudioUtils.mp3ToSilk(AudioUtils.java:42)
	at mider-bot-0.1.8-bundled-silk4j.mirai2.jar//org.mider.produce.core.utils.StreamUtilsKt.generateAudioStreamByFormatMode(StreamUtils.kt:82)
	at mider-bot-0.1.8-bundled-silk4j.mirai2.jar//org.mider.produce.core.LogicKt$generate$2.invokeSuspend(logic.kt:61)
	at mider-bot-0.1.8-bundled-silk4j.mirai2.jar//org.mider.produce.core.LogicKt$generate$2.invoke(logic.kt)
	at mider-bot-0.1.8-bundled-silk4j.mirai2.jar//org.mider.produce.core.LogicKt$generate$2.invoke(logic.kt)
	at mider-bot-0.1.8-bundled-silk4j.mirai2.jar//org.mider.produce.core.utils.TimeUtilsKt.time(TimeUtils.kt:22)
	at mider-bot-0.1.8-bundled-silk4j.mirai2.jar//org.mider.produce.core.LogicKt.generate(logic.kt:13)
	at mider-bot-0.1.8-bundled-silk4j.mirai2.jar//org.mider.produce.bot.HandleKt$handle$2.invokeSuspend(handle.kt:46)
	at mider-bot-0.1.8-bundled-silk4j.mirai2.jar//org.mider.produce.bot.HandleKt$handle$2.invoke(handle.kt)
	at mider-bot-0.1.8-bundled-silk4j.mirai2.jar//org.mider.produce.bot.HandleKt$handle$2.invoke(handle.kt)
	at mider-bot-0.1.8-bundled-silk4j.mirai2.jar//org.mider.produce.core.utils.StringUtilsKt.matchRegex(StringUtils.kt:18)
	at mider-bot-0.1.8-bundled-silk4j.mirai2.jar//org.mider.produce.bot.HandleKt.handle(handle.kt:39)
	at mider-bot-0.1.8-bundled-silk4j.mirai2.jar//org.mider.produce.bot.HandleKt$handle$1.invokeSuspend(handle.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
```

**Comment by whiterasbk** [comment]
@chenxi050402 在 [v0.1.8-patch](https://github.com/whiterasbk/MiraiMidiProduce/releases/tag/v0.1.8-patch) 中已修复
