### ISSUE TITLE
bpm过快时无法生成

### ISSUE THREAD

**Issue by OctoFlareDev** [whiterasbk/MiraiMidiProduce#5]
bpm过大时出现 解析错误>UnsupportedAudioFileException>Stream of unsupported format

`2022-07-14 23:14:54 I/MidiProduce: sounds begin
2022-07-14 23:14:54 E/MidiProduce: javax.sound.sampled.UnsupportedAudioFileException: Stream of unsupported format
javax.sound.sampled.UnsupportedAudioFileException: Stream of unsupported format
        at java.desktop/javax.sound.sampled.AudioSystem.getAudioInputStream(AudioSystem.java:1014)
        at MidiProduce-0.1.6-bundled-silk4j.jar//bot.music.whiter.UtilsKt.midi2mp3Stream(utils.kt:31)
        at MidiProduce-0.1.6-bundled-silk4j.jar//bot.music.whiter.UtilsKt.midi2mp3Stream$default(utils.kt:30)
        at MidiProduce-0.1.6-bundled-silk4j.jar//bot.music.whiter.UtilsKt.generateAudioStreamByFormatMode(utils.kt:228)
        at MidiProduce-0.1.6-bundled-silk4j.jar//bot.music.whiter.MidiProduce$generate$2$2.invokeSuspend(MidiProduce.kt:273)
        at MidiProduce-0.1.6-bundled-silk4j.jar//bot.music.whiter.MidiProduce$generate$2$2.invoke(MidiProduce.kt)
        at MidiProduce-0.1.6-bundled-silk4j.jar//bot.music.whiter.MidiProduce$generate$2$2.invoke(MidiProduce.kt)
        at MidiProduce-0.1.6-bundled-silk4j.jar//bot.music.whiter.UtilsKt.time(utils.kt:166)
        at MidiProduce-0.1.6-bundled-silk4j.jar//bot.music.whiter.MidiProduce$generate$2.invokeSuspend(MidiProduce.kt:138)
        at MidiProduce-0.1.6-bundled-silk4j.jar//bot.music.whiter.MidiProduce$generate$2.invoke(MidiProduce.kt)
        at MidiProduce-0.1.6-bundled-silk4j.jar//bot.music.whiter.MidiProduce$generate$2.invoke(MidiProduce.kt)
        at MidiProduce-0.1.6-bundled-silk4j.jar//bot.music.whiter.UtilsKt.matchRegex(utils.kt:24)
        at MidiProduce-0.1.6-bundled-silk4j.jar//bot.music.whiter.MidiProduce.generate(MidiProduce.kt:131)
        at MidiProduce-0.1.6-bundled-silk4j.jar//bot.music.whiter.MidiProduce.access$generate(MidiProduce.kt:26)
        at MidiProduce-0.1.6-bundled-silk4j.jar//bot.music.whiter.MidiProduce$onEnable$process$1.invokeSuspend(MidiProduce.kt:56)
        at MidiProduce-0.1.6-bundled-silk4j.jar//bot.music.whiter.MidiProduce$onEnable$process$1.invoke(MidiProduce.kt)
        at MidiProduce-0.1.6-bundled-silk4j.jar//bot.music.whiter.MidiProduce$onEnable$process$1.invoke(MidiProduce.kt)
        at MidiProduce-0.1.6-bundled-silk4j.jar//bot.music.whiter.MidiProduce$onEnable$2.invokeSuspend(MidiProduce.kt:67)
        at MidiProduce-0.1.6-bundled-silk4j.jar//bot.music.whiter.MidiProduce$onEnable$2.invoke(MidiProduce.kt)
        at MidiProduce-0.1.6-bundled-silk4j.jar//bot.music.whiter.MidiProduce$onEnable$2.invoke(MidiProduce.kt)
        at net.mamoe.mirai.event.EventChannel$subscribeAlways$1.invokeSuspend(EventChannel.kt:455)
        at net.mamoe.mirai.event.EventChannel$subscribeAlways$1.invoke(EventChannel.kt)
        at net.mamoe.mirai.event.EventChannel$subscribeAlways$1.invoke(EventChannel.kt)
        at net.mamoe.mirai.event.EventChannel$filter$1$intercepted$thisIntercepted$1.invokeSuspend(EventChannel.kt:169)
        at net.mamoe.mirai.event.EventChannel$filter$1$intercepted$thisIntercepted$1.invoke(EventChannel.kt)
        at net.mamoe.mirai.event.EventChannel$filter$1$intercepted$thisIntercepted$1.invoke(EventChannel.kt)
        at net.mamoe.mirai.internal.event.Handler$onEvent$2.invokeSuspend(InternalEventListeners.kt:50)
        at net.mamoe.mirai.internal.event.Handler$onEvent$2.invoke(InternalEventListeners.kt)
        at net.mamoe.mirai.internal.event.Handler$onEvent$2.invoke(InternalEventListeners.kt)
        at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:89)
        at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:166)
        at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
        at net.mamoe.mirai.internal.event.Handler.onEvent(InternalEventListeners.kt:50)
        at net.mamoe.mirai.internal.event.InternalEventListenersKt.process(InternalEventListeners.kt:166)
        at net.mamoe.mirai.internal.event.InternalEventListenersKt.callAndRemoveIfRequired(InternalEventListeners.kt:115)
        at net.mamoe.mirai.internal.event.InternalEventListenersKt$callAndRemoveIfRequired$1.invokeSuspend(InternalEventListeners.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.UndispatchedCoroutine.afterResume(CoroutineContext.kt:202)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)`

**Comment by whiterasbk** [comment]
提供一下导致出错的音符序列

**Comment by OctoFlareDev** [comment]
```
>1072b>OOOo#f:#c#f:#c#f:#c#f:#c#f:#c#f:#c#f:#co#f#f:e#f:e#f:e#f:e#f:e#f:e#f:e#d:#f#d:#f#d:#f#d:#f#d:#f#d:#f#d:#f#d:#f#g:#c:#C3#g:#c:#C3a:#c:#C3a:#c:#C3a:#c:#C3a:#c:#C3a:#c:#C3a:#c:#C3a:a:A3a:a:A3a:a:A3a:a:A3a:a:A3a:a:A3a:a:A3a:a:A3e:#g:#G3e:#g:#G3e:#g:#G3e:#g:#G3e:#c:#C3e:#c:#C3e:#c:#C3e:#c:#C3e:#d:#D3e:#d:#D3e:#d:#D3e:#d:#D3e:e:E3e:e:E3e:e:E3e:e:E3#d:#f:#F3#d:#f:#F3#d:#f:#F3#d:#f:#F3#d:#f:#F3#d:#f:#F3#d:#f:#F3#d:#f:#F3e:#c:#C3e:#c:#C3e:#c:#C3e:#c:#C3e:#c:#C3e:#c:#C3e:#c:#C3e:#c:#C3#f:#f:#F3#f:#f:#F3#f:#f:#F3#f:#f:#F3#f:#f:#F3#f:#f:#F3#f:#f:#F3#f:#F3e:e:E3#f:e:E3#f:e:E3#f:e:E3#f:e:E3#f:e:E3#f:e:E3#f:e:E3#f:#c:#C3#f:#c:#C3#f:#c:#C3#f:#c:#C3#f:#c:#C3#f:#c:#C3#c:#C3#c:#C3B3:b:B3#c:b:B3#c:b:B3#c:b:B3#c:b:B3#c:b:B3#c:b:B3#c:b:B3b:B3b:B3b:B3b:B3b:B3b:B3b:B3b:B3B3:#f:#F3B3:#f:#F3B3:#f:#F3B3:#f:#F3B3:#g:#G3B3:#g:#G3B3:#g:#G3#g:#G3B3:#f:#F3B3:#f:#F3B3:#f:#F3B3:#f:#F3B3:#f:#F3B3:#f:#F3B3:#f:#F3#f:#F3#c:e:E3#c:e:E3#c:e:E3#c:e:E3#c:e:E3#c:e:E3#c:e:E3e:E3#d:#d:#D3#d:#d:#D3#d:#d:#D3#d:#d:#D3#d:#d:#D3#d:#d:#D3#d:#d:#D3#d:#D3e:#d:#D3e:#d:#D3e:#d:#D3e:#d:#D3e:#d:#D3e:#d:#D3e:#d:#D3#d:#D3
```

**Comment by whiterasbk** [comment]
@chenxi050402 
bpm 是通过转换到tempo作为硬编码写入midi文件的, 在使用系统内置的midi解析器可能会出现这类问题, 不妨试试用改变音符时值的方式调整速度
```shell
>g;64x>OOOo#f:#c#f:#c#f...
```
